[package]
name = "racelab"
version = "0.1.0"
description = "RaceLab telemetry desktop application"
authors = ["Taha Gürvardar"]
edition = "2021"

[lib]
name = "racelab_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
