// Deterministic, synthetic Phase D UI fixtures. These are layout examples,
// never captured telemetry or evidence of acceptance in the game.
import type { F1SessionDetail, F1RecorderStatus } from "../src/f1-sessions.ts";

export function f1Detail(id = "f1-review-race"): F1SessionDetail {
  const started = 1_791_030_000_000;
  const stint = { end_lap: 2, actual_compound: 16, visual_compound: 16 };
  return {
    session: {
      racelab_session: {
        envelope_version: 1,
        session_id: id,
        game: "f1_25",
        status: "completed",
        started_at_unix_ms: started,
        ended_at_unix_ms: started + 182_000,
        completion_reason: "final_classification",
        game_session_identity: {
          kind: "f1_session_uid",
          value: "2396549747549880658",
        },
        created_by_racelab_version: "1.1.0",
      },
      f1_25: {
        schema_version: 1,
        session_uid: "2396549747549880658",
        player_car_index: 0,
        protocol: {
          packet_format: 2025,
          game_year: 25,
          game_major_version: 1,
          game_minor_version: 12,
        },
        duration_ms: 182_000,
        sample_rate_hz: 10,
        sample_schema_version: 1,
        context_at_start: null,
        context_latest: {
          received_unix_ms: started + 180_000,
          session_time: 180,
          weather: 0,
          track_temperature_c: 32,
          air_temperature_c: 21,
          total_laps: 2,
          track_length_m: 5891,
          session_type: 10,
          track_id: 7,
          formula: 0,
          session_time_left_s: 0,
          session_duration_s: 182,
          pit_speed_limit_kmh: 80,
          game_paused: 0,
          is_spectating: 0,
          safety_car_status: 0,
          network_game: 0,
          ai_difficulty: 80,
          game_mode: 0,
          rule_set: 0,
          num_safety_car_periods: 0,
          num_virtual_safety_car_periods: 0,
          num_red_flag_periods: 0,
          sector2_lap_distance_start_m: 1700,
          sector3_lap_distance_start_m: 3900,
          num_weather_forecast_samples: 0,
          forecast: [],
        },
        participant: {
          num_active_cars: 22,
          ai_controlled: 0,
          team_id: 0,
          my_team: 0,
          race_number: 44,
        },
        time_trial: null,
        damage_latest: null,
        end_signals: {
          session_started_event: true,
          session_ended_event: false,
          chequered_flag_event: true,
          final_classification: true,
        },
        families: [
          {
            packet_id: 11,
            observed_updates: 3,
            first_received_unix_ms: started,
            last_received_unix_ms: started + 180_000,
          },
        ],
        integrity: {
          sample_count: 1820,
          idle_ticks: 0,
          late_ticks: 0,
          events_stored: 2,
          events_over_cap: 0,
          events_missed: 0,
          button_events_ignored: 6,
          out_of_order_dropped: 0,
          telemetry_gaps: 0,
          lap_count: 2,
          write_error: null,
        },
        recovery: null,
      },
    },
    labels: {
      track: { raw: 7, label: "Silverstone" },
      session_type: { raw: 10, label: "Race" },
      weather: { raw: 0, label: "Clear" },
      formula: { raw: 0, label: "F1 Modern" },
      safety_car_status: { raw: 0, label: "No safety car" },
      network_game: { raw: 0, label: "Offline" },
      game_mode: null,
      rule_set: null,
      team: { raw: 0, label: "Mercedes" },
      result_status: { raw: 3, label: "Finished" },
      result_reason: null,
    },
    laps: {
      schema_version: 1,
      best_lap_time_lap_num: 1,
      best_sector1_lap_num: 1,
      best_sector2_lap_num: 1,
      best_sector3_lap_num: 1,
      history_num_laps: 2,
      lap_positions: [
        { lap_index: 0, position: 3 },
        { lap_index: 1, position: 2 },
      ],
      laps: [1, 2].map((number) => ({
        lap_number: number,
        source: number === 1 ? "session_history" : "lap_data",
        lap_time_ms: number === 1 ? 91_234 : 92_456,
        sector1_ms: 30_000,
        sector2_ms: 31_000,
        sector3_ms: number === 1 ? 30_234 : 31_456,
        valid_bit_flags: number === 1 ? 15 : null,
        lap_valid: number === 1 ? true : null,
        sector1_valid: number === 1 ? true : null,
        sector2_valid: number === 1 ? true : null,
        sector3_valid: number === 1 ? true : null,
        position_at_start: 3,
        position_at_end: 2,
        recorded_at_monotonic_ms: number * 91_000,
      })),
    },
    tyres: {
      schema_version: 1,
      stints: [stint],
      tyre_sets: null,
      fitted_changes: [],
    },
    stints: [{ stint, actual_label: "C5", visual_label: "Soft" }],
    result: {
      schema_version: 1,
      received_unix_ms: started + 182_000,
      num_cars: 22,
      player: {
        position: 2,
        num_laps: 2,
        grid_position: 3,
        points: 18,
        num_pit_stops: 0,
        result_status: 3,
        result_reason: 0,
        best_lap_time_ms: 91_234,
        total_race_time_s: 183.69,
        penalties_time_s: 0,
        num_penalties: 0,
        num_tyre_stints: 1,
        stints: [stint],
      },
    },
    events: [
      {
        sequence: 1,
        monotonic_ms: 0,
        session_time: 0,
        code: "SSTA",
        details: { kind: "session_started" },
        vehicles: [],
      },
      {
        sequence: 2,
        monotonic_ms: 91_234,
        session_time: 91.234,
        code: "FTLP",
        details: { kind: "fastest_lap", vehicle_idx: 0, lap_time_s: 91.234 },
        vehicles: [{ index: 0, is_player: true }],
      },
    ],
    events_total: 2,
    events_not_shown: 0,
    unreadable_files: [],
  };
}

export function f1Recorder(recording = false): F1RecorderStatus {
  return {
    revision: 1,
    enabled: true,
    phase: recording ? "recording" : "idle",
    recording,
    sessions_directory: "sessions",
    session_id: recording ? "f1-review-race" : null,
    session_uid: recording ? "2396549747549880658" : null,
    started_at_unix_ms: recording ? 1_791_030_000_000 : null,
    duration_ms: recording ? 65_000 : 0,
    samples_written: recording ? 650 : 0,
    events_stored: recording ? 2 : 0,
    laps: recording ? 1 : 0,
    waiting_reason: recording ? null : "no_f1_packets",
    grace_remaining_ms: null,
    ending_reason: null,
    track_label: recording ? "Silverstone" : null,
    session_type_label: recording ? "Race" : null,
    completed_sessions: 1,
    last_completed_session_id: "f1-review-completed",
    last_completion_reason: "final_classification",
    sessions_refused_by_owner: 0,
    recording_owner: recording ? "f1_25" : null,
    last_error: null,
  };
}
